### ISSUE TITLE
Update `npm ls` to use `Arborist`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#103]
- investigate how `npm fund` was migrated
- implement the current behavior of `npm v6`

**Comment by ruyadorno** [comment]
Backed from the work on this until we can figure out in a more fundamental level how to move forward with breaking changes in v7, made the effort of documenting the surface of arguments/features of `npm ls` in particular: https://github.com/npm/cli/blob/848d959b1c5512a3b2f8f25fe6aa3c3a1cfe3879/notes/lib/ls.md

**Comment by darcyclarke** [comment]
Update: This work was completed via the following PRs:
- https://github.com/npm/cli/pull/1547 
- https://github.com/npm/cli/pull/1545
- https://github.com/npm/cli/pull/1512
