### ISSUE TITLE
Remove references/dependency on `process.umask()`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#119]
- [ ] remove `process.umask()` from `tar` (or update `tar` if it's already removed in latest versions)
- [ ] remove `process.umask()` everywhere in the cli (ex. `lib/utils/config.js`)

Node deprecation ref: https://github.com/nodejs/node/commit/60c4c2b6c5

**Comment by darcyclarke** [comment]
Good context on this change/work can be found here: https://github.com/nodejs/node/issues/32321

**Comment by darcyclarke** [comment]
Other reference to thread: https://github.com/npm/cli/issues/1103#issuecomment-608601532

**Comment by bonkydog** [comment]
OK, I'm starting work on this in pacote.
