### ISSUE TITLE
Check for audit errors on lib/utils/reify-output.js 

### ISSUE THREAD

**Issue by ruyadorno** [npm/statusboard#125]
From: https://github.com/npm/cli/pull/1311#discussion_r435630245

> Note: we need to check for arb.auditReport.error to see if there was an error loading the audit report. Otherwise it'll look like an audit ran and found no vulns, when really it's just that the audit service is unreachable or something.

**Comment by wraithgar** [comment]
audit-report.js checks for the error attribute now on the audit report and displays errors accordingly.
