### ISSUE TITLE
Fix broken package/repository references

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#16]
- [ ] Update all references that may be pointing to ex-employee's copies of our projects (ex. Coveralls references to Kat's copy of `make-fetch-happen` etc.)

**Comment by ruyadorno** [comment]
Following the lead from **make-fetch-happen**: https://github.com/npm/make-fetch-happen/commit/93ce89df47b014470b5edf88560d9fbf3b556d08 I went ahead and cleaned up the **libnpm** series of repos:

- https://github.com/npm/libnpmaccess/commit/8e9e747744e5057c356e78fd1f45d4da6b7a1735
- https://github.com/npm/libnpmteam/commit/fcc796ea44e48ad975707688cd833a5c52955f08
- https://github.com/npm/libnpmsearch/commit/c503a89239f126670b9d9287cb375f28b67fe7e4
- https://github.com/npm/libnpmorg/commit/bb107d07741f9868514d39f0850f73bf1d7f1780
- https://github.com/npm/libnpmhook/commit/a0fdf7ea7ba1a4ce34cc586d7c9be0fc59ea4c64
- https://github.com/npm/libnpmpublish/commit/3010b938052180af07338933d2d2b8dc83624c8e
- https://github.com/npm/libnpmconfig/commit/e9b201772fc461dd66b0b65a768e1f888273c302
