### ISSUE TITLE
[FEATURE] `npm publish` more information / gated command

### ISSUE THREAD

**Issue by mikemimik** [npm/statusboard#17]
# What / Why

Curerntly `npm publish` **just works** but mistakes can happen and people don't wall know about `--dry-run` which adds some additional details _without_ publishing. It would be great if `npm publish` had a gated `[N/y]` input, and would also display the output of `--dry-run` by default. This would allow the user to inspect before publishing. A `--yes` flag should be added to allow ci to continue to function correctly.

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by darcyclarke** [comment]
### Actions
- [ ] @mikemimik create a question issue and/or make a PR against npm/rfcs
- [ ] @mikemimik close this issue

**Comment by darcyclarke** [comment]
Closing as this is better served as an RFC issue/design doc. We also did accept a similar "publish prompt" RFC a little while back: https://github.com/npm/rfcs/blob/latest/accepted/0028-publish-prompt.md
