### ISSUE TITLE
v7(docs): search

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#243]
- [x] test functionality of command
- [x] review accuracy of docs
- [x] update where necessary
- [x] add or update examples
- [x] spell & grammar check (ex. [grammarly](https://app.grammarly.com/) or [grammarcheck](https://www.grammarcheck.net/editor/))

**Comment by wraithgar** [comment]
The "a note on caching" was added here https://github.com/npm/cli/commit/9ca18ada7cc1c10b2d32bbb59d5a99dd1c743109#diff-5354876ee71ad858356b5c4e2e513d0201927b1aca6ba55eece0dc92c0ae722b and does not appear to ever have had content.
