### ISSUE TITLE
Fix implementation details for `.env` & `.wubwubrc` file interact

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#25]
- [ ] Work with Andri about implementation details
- [ ] Update implementation details inside `./kv-store.js`

**Comment by mikemimik** [comment]
The current implementation of developer flow is to run an "environment setup command" which will use the `configuration.tpl` file and pull values from an `etcd` instance to generate a `.env` file. We're attempting to augment that by creating another file (`.wubwubrc`) which will contain key/value pairs which should _act like an `etcd` source_. This means the "environment setup command" should pull values from the staging `etcd` instance, and then merge the values from the separate configuration file (`.wubwubrc`) and then generate the `.env` file. 

#### Problem Statement
There is currently no tool designed to do this.

#### Potential Solution
Currently we're using `mkenv` tool to read the `configuration.tpl` file and fetch values from an `etcd` instance. This tool could be modified to also fetch values from a separate configuration location. The "merge" capability already exists inside the tool.

**Comment by darcyclarke** [comment]
Closing this as it is no longer a responsibility of our team.
