### ISSUE TITLE
v7(docs): unpublish

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#253]
- [x] test functionality of command
- [x] review accuracy of docs
- [x] update where necessary
- [x] add or update examples
- [x] spell & grammar check (ex. [grammarly](https://app.grammarly.com/) or [grammarcheck](https://www.grammarcheck.net/editor/))

**Comment by ruyadorno** [comment]
https://github.com/npm/cli/issues/1880#issuecomment-723473753
