### ISSUE TITLE
v7(docs): update

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#254]
- [x] test functionality of command
- [x] review accuracy of docs
- [x] update where necessary
- [x] add or update examples
- [x] spell & grammar check (ex. [grammarly](https://app.grammarly.com/) or [grammarcheck](https://www.grammarcheck.net/editor/))

**Comment by ruyadorno** [comment]
NOTE: Make sure to update any refs to `--depth` ref: https://github.com/npm/cli/pull/2440
