### ISSUE TITLE
v7(docs):  cli/docs/content/using-npm/config.md 

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#265]
- [ ] test functionality of command
- [ ] review accuracy of docs
- [ ] update where necessary
- [ ] add or update examples
- [ ] spell & grammar check (ex. [grammarly](https://app.grammarly.com/) or [grammarcheck](https://www.grammarcheck.net/editor/))

**Comment by wraithgar** [comment]
From https://github.com/npm/cli/issues/2089

Problem:
1.) In the config documentation - https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps - --omit is mentioned but no such option is presented in the list of option on the right side. Please add documentation for omit option.

2.) It seems there is related option to omit - include. Are these options targeted for same usage? E.g. Is include=[prod,dev,optional] same as omit=[peer]? Behavior of resolving dependency graph and installing packages is same for both options?
