### ISSUE TITLE
Bring test coverage to 100% on `make-fetch-happen`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#28]
- [x] Write tests to bring coverage on [`make-fetch-happen`](https://github.com/npm/make-fetch-happen) up to 100% ✅

- [x] Fix the url reference in badges

**Comment by mikemimik** [comment]
[This pull-request](https://github.com/npm/make-fetch-happen/pull/14) brings coverage to 100% and closes this epic.
