### ISSUE TITLE
task(workspaces): update `outdated`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#303]
### Exit criteria 

* Coupled to & blocked by [#273 - adding filtering to `Arborist`](https://github.com/npm/statusboard/issues/273)
* [x] `outdated` should be able to operate with a set of workspaces defined
* [x] Tests are written validating this behavior
* [x] Documentation is updated to reflect this change (ex. metadata/label showing the degree of workspace support)

**Comment by glen-84** [comment]
@ruyadorno,

Is this supposed to be working now?

![image](https://user-images.githubusercontent.com/261509/119130107-0a610f00-ba38-11eb-92d3-02b3246b425c.png)

`npm ls` doesn't seem to work either.

Windows 10, Node.js 14.17.0.

**Comment by ruyadorno** [comment]
hi @glen-84 it would be nice to also see your project level `package.json` to make sure workspaces are properly configured, is any workspace-functionality working at all in this project? what about running `npm run --ws` from the root level? it would be nice to also maybe see a result for `npm ls`, etc

**Comment by glen-84** [comment]
@ruyadorno,

I just wrote out all that information and then decided to add a `name` to the workspace `package.json` files ... and now it works.

1. Is this a requirement?
2. Doesn't the workspaces configuration refer to folder paths/names and not package names?
3. Why does `npm run` work without naming the workspace packages?

Thanks for your help.

**Comment by glen-84** [comment]
@ruyadorno,

Can you please let me know if the above is a bug, or if adding package names to workspace projects it a requirement?

This will inform my decision on whether to wait for a fix, or add the names.

Thanks.
