### ISSUE TITLE
refactor(npmlog): consolidate logging into npm.js itself

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#306]
Like we did for `npm.out()` we should consolidate the use of `npmlog` into `npm.log`

**Comment by isaacs** [comment]
Once this and https://github.com/npm/statusboard/issues/366 done, then `npm.log = require('proc-log')`, and everything is going through a single decoupled channel for logging.

**Comment by wraithgar** [comment]
This is not really warranted based on the current direction @lukekarrys is taking w/ the npmlog refactoring work
