### ISSUE TITLE
fix: running `npm` commands in `npm exec`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#313]
### Current Behavior
* `npm exec -ws -c 'npm whoami'` fails because `workspaces` is passed into the subprocess as an environment var
* `npm exec -w foo -c 'npm whoami'` fails because `workspace` is passed into the subprocess as an environment var

### Expected Behavior
* `npm exec` should not pass on `workspace` or `workspaces` config into the env

### Exit Criteria
* [ ] bug should be fixed
* [ ] documentation should exist for `npm exec` that explicitly outlines the absence of those envs from the subprocess
* [ ] documentation should be updated to use `--ws` wherever `-ws` currently is marked (ex. examples)

**Comment by ruyadorno** [comment]
issue seems to have been fixed in between the original post and now, just tested with `npm@7.10.0` and it works as intended:

```sh
$ npm exec -ws -c 'npm whoami'
ruyadorno
ruyadorno
ruyadorno
ruyadorno
ruyadorno

$ npm exec -ws -c 'npm ls'
a@1.0.0 <path>/test-workspaces-run-script/core/a
└── (empty)

b@1.0.0 <path>/test-workspaces-run-script/core/b
└── (empty)

c@1.0.0 <path>/test-workspaces-run-script/packages/c
└── (empty)

d@1.0.0 <path>/test-workspaces-run-script/packages/d
└── (empty)

e@1.0.0 <path>/test-workspaces-run-script/packages/e
└── (empty)

$ npm exec -ws -c 'npm fund'
a@1.0.0

b@1.0.0

c@1.0.0

d@1.0.0

e@1.0.0

# Single workspace:
$ npm exec -w a -c 'npm whoami'
ruyadorno

```
