### ISSUE TITLE
Add ownership files to tracked projects/repos

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#319]
- Blocked/dependent on https://github.com/npm/statusboard/issues/318
- [ ] Once projects have been audited, file PRs against set to ensure `CODEOWNER` files have been added & specify the `@npm-cli` team (ref. https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)

**Comment by wraithgar** [comment]
template-oss manages codeowners now
