### ISSUE TITLE
fix exec arg handling and factor it better

### ISSUE THREAD

**Issue by isaacs** [npm/statusboard#363]
# 1. Create matrix of scenarios

Condition matrix:

- shell type:
  - posix sh-like (any differences between bash vs sh vs zsh?)
  - windows cmd (regular old binary)
  - windows cmd (batch file)
  - windows powershell? (aside: maybe we could fix some stuff by using powershell instead of bash?  or maybe that'd make things worse?  idk, but it is ubiquitous now.)
- command being run:
  - `npx some-package some args`
  - `npm exec some-package some args`
  - `npx --package some-package some command`
  - `npm exec --package some-package some-command`
  - `npx --package some-package -c 'some-command'`
  - `npm exec --package some-package -c 'some-command'`
  - `npm run foo` (where `scripts.foo` is `some-command some-args`)
  - `npm run foo -- some-args`
- funkiness of args (all of these are the unquoted actual string value in `<code>` block, so if you see `'`, then it has `'` chars in it)
  - `$1` (ie: get literal $1 as the arg)
  - `"$1"` (arg has double-quotes)
  - `'$1'` (arg has single-quotes)
  - `\$1`
  - `--arg="$1"`
  - `--arg=npm exec -c "$1"`
  - `--arg=npm exec -c '$1'`
  - `'--arg=npm exec -c "$1"'`

For each item in the matrix, identify the expected result, and the current result, and the breakage we might expect by replacing the current result with the expected result (if any).

# 2. Factor this stuff better

- [x] Make `@npmcli/promise-spawn` _just_ a Promisey wrapper around `child_process.spawn` (npm/promise-spawn#6)
- [ ] Write `@npmcli/exec` which runs things "the npm way" (puts `node_modules/.bin` in the PATH, uses `infer-owner` when root, gets environment vars from `package.json` if there's one in the execution cwd, etc.) (npm/exec#1, npm/exec#2, npm/exec#3, npm/exec#4, npm/exec#5, npm/exec#6)
- [ ] Make `@npmcli/run-script` a lightweight wrapper around `@npmcli/exec` that just reads package.json and then calls `@npmcli/exec` with the appropriate command argument.
- [ ] Refactor `libnpmexec` to use `@npmcli/exec` instead of doing the weird `@npmcli/run-script` fake script dance.

# 3. Use puka better, and only for arguments

We currently escape arguments with `JSON.stringify()` which makes it impossible to pass in something like `"$1"` as an argument, because the `"` chars get escaped, and even if you escape the `$`, then the backslashes _also_ get escaped, so instead of `"\$1"` you get `\"\\$1\"`.

Puka author is saying he's going to do the "figure out if it's a batch file or regular binary on Windows" work for us, so we should take him up on that offer.

# 4. Consider using Powershell instead of cmd.exe

It's ubiquitous now, so if that provides any benefits, we could consider it.  (Not sure it does, but worth looking into.)

**Comment by wraithgar** [comment]
This is largely done except for the powershell consideration.
