### ISSUE TITLE
GitHub action to verify autogenerated doc content for pull requests

### ISSUE THREAD

**Issue by gimli01** [npm/statusboard#364]
## Description
We want a GitHub action to run a series of checks against PR branches for `release-next` and `latest`. 

1. Check PR follows conventional PR title format
2. Check if `postsnap` gives us a clean working directory

## Exit Criterias

**Clean git directory**

- run GH action on pull request for branch `release-next`
- checkout PR branch & install dependencies
- run `touch lib/utils/config/definitions; npm run postsnap`
- if `git status -s` has changes, we fail. otherwise, the pr passes

**PR title format**

- title of PR should follow conventional commits format

**Comment by wraithgar** [comment]
Our PR linting is working as intended now
