### ISSUE TITLE
fix(automation): node prs for >=16.x should point at `staging` branches

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#385]
### Summary
Currently we're pointing the Node.js Dep Update PRs we created against the `master` branch which may not have the latest or staged changes as a maintainer is queuing up a release (ex. https://github.com/nodejs/node/pull/39813).

### Change
- [ ] Update references to `master` to be the relevant `staging` branch for the `npm` release (ref. https://github.com/npm/cli/blob/latest/.github/workflows/create-cli-deps-pr.yml#L30)

### Reference:
- https://github.com/nodejs/node/pull/39813#issuecomment-903222892

**Comment by wraithgar** [comment]
we only have a `latest` branch now and the node PRs point to the correct commits/changelogs
