### ISSUE TITLE
Epic: New tree mutation lifecycle event

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#399]
We had discussed adding this sooner rather than later, to help unblock github/github moving to npm@8

**Comment by koddsson** [comment]
Hey @darcyclarke; is this still being worked on? I don't see it in the v9.x initiative list?

**Comment by rowanbeentje** [comment]
@darcyclarke @wraithgar I also checked the v9 list and looked at the commits around the 16th May, and couldn't see anything related - was this closed erroneously, or is support for shrinkwrap-style events officially permanently dropped?

(Trying to work out whether to hang on or to go further into workarounds!)

**Comment by wraithgar** [comment]
It's in https://github.com/npm/statusboard/issues/489 as https://github.com/npm/statusboard/issues/493

**Comment by rowanbeentje** [comment]
Oh even better, _currently_ planned for v8.x! OK, fingers crossed :) Thank you!

**Comment by dgreif** [comment]
It looks like this feature is now available with the [`dependencies` script](https://docs.npmjs.com/cli/v8/using-npm/scripts#dependencies). Is that accurate @wraithgar?

**Comment by wraithgar** [comment]
Yes, and you can see it in action in the [npm package itself](https://github.com/npm/cli/blob/f628431c8a79d7cf00987ca6372dc34d4fbadfcf/package.json#L218).
