### ISSUE TITLE
Epic: refactor npm commands

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#402]
We want to refactor the commands to end up in a place where we can do per-command options and subcommands.

- First refactor will be to move commands into isolated subfolder, clean up module api for each command, and make test pass again (this is the biggest granular change, ideally after this the changes can be smaller and won't require test refactoring)
- Second refactor will be to pull aliases into the subcommands themselves (#305)
- After this we can architect and plan subcommands, and per-command config

**Comment by lukekarrys** [comment]
This is complete @wraithgar 😄

**Comment by wraithgar** [comment]
#305 is still the next step but this isn't an active epic so it's ok to be closed.
