### ISSUE TITLE
release: cut v6 release

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#418]
### Summary
- [ ] modify `npm login` prompt for OTP to align w/ `v8`
- [ ] update production dependencies where possible to mitigate any audit warnings

**Comment by ruyadorno** [comment]
- Release: https://github.com/npm/cli/releases/tag/v6.14.16
- node12 PR: https://github.com/nodejs/node/pull/41601
- node14 PR: https://github.com/nodejs/node/pull/41603
