### ISSUE TITLE
consolidate color and table dependencies

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#421]

**Comment by lukekarrys** [comment]
i did a spike in this and was able to deduce the existing dependencies enough to get to 0 audit warnings. but i also learned the dependencies were each being used for different use cases so consolidating was not possible.

**Comment by darcyclarke** [comment]
### Update
- consolidation was a bit harder then expected
- leaving variants for now
- fixed audit warnings by upgrading versions
