### ISSUE TITLE
Epic: Display Progress

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#422]
Ref: #366, #421 

- [x] Merge cli PRs to exec and arborist progress workspaces
- [ ] Remove npmlog
- [ ] Implement progress in display class

**Comment by darcyclarke** [comment]
### Update
- `npmlog` is left in one place
- display class work is being backlogged

**Comment by darcyclarke** [comment]
### Update (2022-04-04)
- potential change for v9 (as a breaking change) would be to switch to spinner vs. trying to maintain a progress bar (ex. migrating to `proggy`)

**Comment by wraithgar** [comment]
https://github.com/npm/statusboard/issues/810
