### ISSUE TITLE
Add pretty-printed WARN message upon non-2FA-enabled-publish

### ISSUE THREAD

**Issue by ruyadorno** [npm/statusboard#43]
In order to better promote adoption of 2FA among package publishers we could add a catchy-looking warning message that gets printed to the user upon every publish (if that user has disabled 2FA publish). Some other optional ideas:
- Add a Y/N prompt confirmation (in order to guarantee users read the warning info)
- Add a direct link to: `https://www.npmjs.com/settings/<username>/tokens/create`

**Comment by wraithgar** [comment]
This is no longer on our roadmap.  2fa adoption is driven by product right now and we can implement whatever they suggest in the future.
