### ISSUE TITLE
[FEATURE] add column for ci/cd information

### ISSUE THREAD

**Issue by mikemimik** [npm/statusboard#44]
# What / Why

At a glance would be nice to see if the repository is using travis, appvoyer, or github actions. More specifically what matrix of builds it's running.

## When

Should be displayed in a column on the status board.

## Where

* n/a

### Current Behavior

Only the build status of the "default" branch is shown. No information about the repositories build matrixes are present.

### Expected Behavior

Pulling the files content from a repository should be able to find at a top level if the `.travis.yml` or `.appvoyer.yml` or `.github/workflow/` files exist. Travis and Appvoyer would be the easiest of the files to parse, you can just look for `os:` and `nodejs` versions, to determine the build matrix. The github actions will be a little more work. We'll have to find the `on:` field and look for `push` or `pull_request` for the "default" branch and review the `strategy` of that to determine the build matrix.

## References

* n/a

**Comment by darcyclarke** [comment]
Closing as we've centralized on GitHub Actions & we don't need this atm.
