### ISSUE TITLE
BREAKING CHANGE(explain): Remove path support

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#447]

**Comment by lukekarrys** [comment]
Does anyone have context on what this means?

**Comment by ljharb** [comment]
I think it means `npm explain ./relative/path` should stop working, so that `npm explain` only takes a package name?

**Comment by darcyclarke** [comment]
Closing this - as conversations with the team made it clear this was meant as a placeholder to ensure we updated docs around package specs. `npm explain` should support whatever is considered a valid package spec (ie. there shouldn't be any work to do here)
