### ISSUE TITLE
BREAKING CHANGE(config): map legacy options to `--location` & `--strategy`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#458]
- [x] remove `--local` config
- [x] remove `--global-style`
- [x] remove `--legacy-bundling`
- [x] add `--strategy` config with four reify mode options:
  - `hoisted` (current default mode)
  - `nested` (formerly `--legacy-bundling` mode, where deps are installed in place - no hoisting)
  - `shallow` (formerly `--global-style` mode, where only direct deps are installed at top-level `node_modules`)
  - `linked` (future isolated mode) 
- [x] `--global` should now set `--location=global` & `--strategy=nested` when `true`
- [x] all relevant code paths should use `--location` & `--strategy` in place of their legacy counterparts

**Comment by fritzy** [comment]
`--strategy` is actually `--install-strategy` to avoid confusion with auth configuration.

`--global` was already setting `--location` in the CLI. While `--global` does set `--install-strategy=shallow` in arborist itself, it does not set `--location` in arborist directly, but within the npm CLI.
