### ISSUE TITLE
feat(query): Add command alongside package selector syntax

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#463]
### Summary
Introduce a much needed top-level command & net-new capabilities for dependency selection/discovery.

### Exit Criteria
- [x] Create new `npm query` command which parses a dependency selector & returns a NodeList
- [x] Add new `.querySelectorAll()` method to `Arborist`'s `Node` class
- [x] Tests are written for new command
- [x] Documentation is written for new command & selector syntax

#### Universal Selectors
    
- [x] `*` universal selector
- [x] `#<name>` dependency selector (equivalent to `[name="..."]`)
- [x] `#<name>@<version>` (equivalent to `[name=<name>]:semver(<version>)`)
- [x] `,` selector list delimiter
- [x] `.` class selector
- [x] `:` pseudo class selector
- [x] `>` direct decendent/child selector
- [x] `~` sibling selector

#### [Attribute Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)

- [x] `[]` attribute selector (ie. existence of attribute)
- [x] `[attribute=value]` attribute value is equivalant...
- [x] `[attribute~=value]` attribute value contains word...
- [x] `[attribute*=value]` attribute value contains string...
- [x] `[attribute|=value]` attribute value is equal to or starts with...
- [x] `[attribute^=value]` attribute value begins with...
- [x] `[attribute$=value]` attribute value ends with...
 
#### Pseudo Selectors
- [x] [`:not(<selector>)`](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)
- [x] [`:has(<selector>)`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)
- [x] [`:is(<selector list>)`](https://developer.mozilla.org/en-US/docs/Web/CSS/:is)
- [x] [`:root`](https://developer.mozilla.org/en-US/docs/Web/CSS/:root) matches the root node/dependency
- [x] [`:scope`](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) matches node/dependency it was queried against
- [x] [`:empty`](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty) when a dependency has no dependencies
- [x] [`:private`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private) when a dependency is private
- [x] `:link` when a dependency is linked
- [x] `:extraneous` when a dependency exists but is not defined as a dependency of any node
- [x] `:invalid` when a dependency version is out of its ancestors specified range
- [x] `:missing` when a dependency is not found on disk
- [x] `:semver(<spec>)` matching a valid [`node-semver`](https://github.com/npm/node-semver) spec
- [x] `:deduped` when a dependency has been deduped
- [x] `:path(<path>)` [glob](https://www.npmjs.com/package/glob) matching based on dependencies path relative to the project
- [x] `:type(<type>)` [based on currently recognized types](https://github.com/npm/npm-package-arg#result-object)
- [x] `:attr(<key>, <attribute selector>)` see below

#### `Array` & `Object` Attribute Selectors

- [x] `Object` Selection:

```css
/* return dependencies that have a `scripts.test` containing `"tap"` */
*:attr(scripts, [test~=tap])
```

- [x] `Array` Attribute Selections:
```css
/* return dependencies that have a keyword that begins with "react" */
*:attr(keywords, [^=react])
```

- [x] `Array` match value Selection:
```css
/* return dependencies that have the exact keyword "react" */
*:attr(keywords, [=react])
```

- [x] `Array` of `Object`s Selection:
```css
/* returns contributors with the email "ruyadorno@github.com" */
*:attr(contributors, [email=ruyadorno@github.com])
```

### Classes/Groups
- [x] `.prod`
- [x] `.dev`
- [x] `.optional`
- [x] `.peer`
- [x] `.bundled`
- [x] `.workspace`

### Links & References
- RFC: https://github.com/npm/rfcs/pull/564
- AST Selector Libraries/Parsers
  - [`estree`](https://github.com/estree/estree)
  - [`abstract-syntax-tree`](https://www.npmjs.com/package/abstract-syntax-tree)
  - [`postcss-selector-parser`](https://www.npmjs.com/package/postcss-selector-parser) / [API](https://github.com/postcss/postcss-selector-parser/blob/master/API.md) 
- [`CSS`](https://www.w3.org/Style/CSS/specs.en.html), [Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) & [Pseudo Class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) Specifications

### Stretch Goals
- create new `@npmcli/queryparser` (or similar name)  to manage syntactical nuances to [the spec](https://github.com/npm/rfcs/pull/564) (ex. hashed package name & semver range de-sugaring)
- `:outdated()` when a dependency has available updates (options for specifying the range, defaults to parent's dependent range)
- `:vulnerable` when a dependency has a `CVE` 
- `:override` when a dependency is an override
  - **Blocked:** `Arborist.loadActul()` needs to be improved for `ovrrides` 
  - Talk with @nlf

**Comment by darcyclarke** [comment]
- `":has(> .workspace)"` unbounded memory consumption
- `:attr([name=value])` arbitrary attribute selection does not work
- support for attribute value case sensitivity (ref. https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax)
  - ex.  `[name=value i]` or  `[name=value I]` 
  - ex.  `[name=value s]` or  `[name=value S]`

**Comment by ljharb** [comment]
Shouldn't values with spaces need to be quoted?

**Comment by wraithgar** [comment]
> Shouldn't values with spaces need to be quoted?

"Adding an i (or I) before the closing bracket causes the value to be compared case-insensitively (for characters within the ASCII range)."

**Comment by ljharb** [comment]
yes, indeed, i deleted my comment - i wasn't aware of that "suffix" feature.

**Comment by wraithgar** [comment]
I *think* I fixed the `has:` bug while consolidating state, found an inconsistency in what was being passed around and fixed it, and the `-w` command that was melting my computer simply returns the correct result quickly now.  Haven't pushed the change yet because I'm still consolidating state.

**Comment by wraithgar** [comment]
@ruyadorno This code has been a treat to refactor.  Every improvement I've made has either been a bugfix (which is inevitable in a codebase this big) or something that was high level and thus would have been inappropriate to even try to do on a first pass PR.
