### ISSUE TITLE
chore(config): Deprecate & warn for `--global` (`--location=global`)

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#496]

**Comment by fritzy** [comment]
https://github.com/npm/cli/pull/4878

**Comment by mscdex** [comment]
Why was the cli `-g`/`--global` flag deprecated (in https://github.com/npm/cli/pull/4879)? Having to do `--location=global` seems overly verbose.

**Comment by darcyclarke** [comment]
@mscdex deprecation does not mean removal (so `npm i -g <pkg>` still works the same way). We're intending to patch this. Going to close this issue & make a new one explaining the details further there (will cross link once it's up)
