### ISSUE TITLE
Standardize "author" & "license" information in all repositories

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#5]
- [ ] `"author": "npm Inc. <support@npmjs.com>"`
- [ ] `"license": "MIT"` or `"license": "ISC"`

> There are some repositories that have a `package.json` with an author set who was a previous employee. This should be changed to the above.

**Comment by HERBOD7** [comment]
@darcyclarke I can do it.

**Comment by darcyclarke** [comment]
@HERBOD7 Appreciate the enthusiasm! Unfortunately, some of these tasks require specific GitHub permissions (and/or, internal discussions) which we've only currently given to npm inc. employees. That might change in the future if we're able to permission community contributors in a way to unlocks those types of capabilities.

**Comment by lukekarrys** [comment]
This is done via `@npmcli/template-oss`
