### ISSUE TITLE
feat(access): Deprecate & warn for subcommands

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#500]
### Summary
We will be removing a number of `npm access` commands in v9 (ref. https://github.com/npm/statusboard/issues/486); show warnings when someone uses them in `v8.x`.

### Exit Criteria

- [x] start throwing a warning for deprecation of `2fa-required`
- [x] start throwing a warning for deprecation of `2fa-not-required`
- [x] start throwing a warning for deprecation of `public`
- [x] start throwing a warning for deprecation of `restricted`
- [x] start throwing a warning for deprecation of `edit`
- [x] start throwing a warning for deprecation of `ls-packages`
- [x] start throwing a warning for deprecation of `ls-collaborators`

**Comment by wraithgar** [comment]
`edit` is not implemented yet so no warning is needed.

```javascript
  async edit () {
    throw new Error('edit subcommand is not implemented yet')
  }
```

**Comment by wraithgar** [comment]
PR implementing this is here, ready for copy editing if needs be https://github.com/npm/cli/pull/5347

**Comment by jaswrks** [comment]
@wraithgar Hi. Was grant / revoke intended to be a part of this and deprecated? If so, do you know what is going to replace them? I don't see any other functionality in the CLI that's equivalent, and these were not deprecated in the latest release.

**Comment by wraithgar** [comment]
Those subcommands are still part of `npm access` and I don't see where they were ever deprecated.


```
~/D/n/c/b/main (latest|✔) $ npm -v
9.3.1
~/D/n/c/b/main (latest|✔) $ npm access -h
Set access level on published packages

Usage:
[...]
npm access grant <read-only|read-write> <scope:team> [<package>]
npm access revoke <scope:team> [<package>]
```

They are also included in the tests that ensure they result in actual http calls to the registry.

**Comment by jaswrks** [comment]
@wraithgar Thanks for confirming. So the docs state they are deprecated, though.
https://docs.npmjs.com/cli/v9/commands/npm-access

```
grant / revoke (deprecated): Add or remove the ability of users and teams to have read-only or read-write access to a package.
```

**Comment by wraithgar** [comment]
Looks like the docs weren't updated to reflect the new v9 api https://github.com/npm/cli/pull/5445
