### ISSUE TITLE
BREAKING CHANGE(install): default to `--install-links=true`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#510]
### Summary
In v7 we stopped installing linked deps, in v8 we added the flag `--install-links` to accommodate this use case. In v9 we should make this the default again (ie. `--install-links=true`)

**Comment by sacummings91** [comment]
Really confused by this change. This seems to break anywhere we are running npm install in docker or CI/CD because we use git submodules. Is this now the expected behavior? Do we always have to do `npm install --no-install-links` now?

**Comment by wraithgar** [comment]
This was reverted in [`npm@9.4.2`](https://github.com/npm/cli/blob/latest/CHANGELOG.md#942-2023-02-07)
