### ISSUE TITLE
feat(config): remove deprecation warning for `auth-type`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#512]
### Summary
Previously we added a deprecation warning for `auth-type` as it was a config queued to be removed but we've recently shipped `webauthn` support under this config meaning it likely needs to persist for some time beyond the next major

### Exit Criteria
- [x] consider changing the deprecation warning to just display when `sso`, `saml` or `oauth` values are passed to `auth-type` (this provides us with a path forward to consolidating these values into a singular `legacy` option)

**Comment by wraithgar** [comment]
we log deprecation on the auth *values* now.
