### ISSUE TITLE
feat(adduser): add deprecation warning

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#513]
### Summary
In v9 we will tease apart `npm login` & `npm register` (& `npm adduser` will become an alias _just_ to registration). Begin showing a warning for `npm login`/`npm adduser` to highlight this change in functionality in the next major.

**Comment by wraithgar** [comment]
```sh
$ npm login
npm WARN adduser `adduser` will be split into `login` and `register in a future version. `adduser` will become an alias of `register`. `login` (currently an alias) will become its own command.
```
