### ISSUE TITLE
fix(config): remove deprecation warning for `--global`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#518]
### Summary
A mistake was made creating [this issue](https://github.com/npm/statusboard/issues/496) & subsequently led to us issuing a warning that `--global` was being removed. For context, `--global` will be changing it's underlying behaivor to map to `--location=global` which maps with existing `--location`-aware commands (ie. `npm config` & in `v9` `npm exec`)

### Exit Criteria
- [x] running `npm` with `--global` should not warn users

### References & Links
- Release (In-Flight): https://github.com/npm/cli/pull/4984
- Original intention https://github.com/npm/statusboard/issues/458
- Mistaken Issue: https://github.com/npm/statusboard/issues/496

**Comment by mscdex** [comment]
@wolfpackt99 Downgrade to v8.10.0?

**Comment by darcyclarke** [comment]
@wolfpackt99 we're shipping a patch right now to remove the deprecation warning as we speak

**Comment by nlf** [comment]
done! published v8.12.1 with this reversed

**Comment by alexrosenfeld10** [comment]
Is this fixed for sure in 8.12.1?

```
-- console output produced during zsh initialization follows --

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
❯ which npm
/Users/alexrosenfeld/.nvm/versions/node/v16.15.1/bin/npm                                                                                                                                                                                            ─╯
❯ npm --version
8.12.1
❯ which node
/Users/alexrosenfeld/.nvm/versions/node/v16.15.1/bin/node
❯ node --version
v16.15.1
```

**Comment by mscdex** [comment]
@alexrosenfeld10 Perhaps the npm in your zsh initialization is a different version? Does executing a global command like `npm ls -g --depth=0` from your shell prompt print the deprecation warning?

**Comment by alexrosenfeld10** [comment]
@mscdex yeah, seems like you're right - the initialization must be using a different version, because after initialization that command runs w/o a warning.
