### ISSUE TITLE
chore: modify cli changelog script to parse subjects and group them appropriately

### ISSUE THREAD

**Issue by nlf** [npm/statusboard#528]
for example, if the commit is `feat(arborist): added something` then we should be able to identify the commit as being related to an arborist deps commit, and place the feat commit as a bullet point there instead of at the top level

current behavior:
```
### Features

  * feat(arborist): added a feature

### Dependencies

  * deps: `@npmcli/arborist@X.Y.Z`
```

desired behavior:
```
### Dependencies

* deps: `@npmcli/arborist@X.Y.Z`
  * feat(arborist): added a feature
```

**Comment by wraithgar** [comment]
The changelog in the cli is working pretty well right now. We can iterate if we want later.
