### ISSUE TITLE
BREAKING CHANGE(config): npm 9 should refuse to set deprecated config items.

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#535]
Our deprecation warnings show items as flags, which means if you `npm config set foo` where `foo` is deprecated you get a warning that implies you used `--foo`.  We can't really change our deprecation warnings because then folks would inevitably complain that `foo` is an invalid param (without the `--`).

A simple solution is to stop allowing `npm config` itself setting deprecated configs.

**Comment by Taishawnk** [comment]
What is the fix?
