### ISSUE TITLE
Initiative: Backport `npm@9.x` in `node@19`

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#586]
### Summary
Make `npm@9.x` available in the latest LTS version of Node.js after roughly ~4 weeks of General Availability to address any critical issues (replacing the unmaintained `npm@8.x` version).

### Exit Criteria
- [ ] On Target Date: Open PR to backport `npm@latest` against the `nodejs/node` `v19` branch

### Links & References
- https://github.com/nodejs/Release/issues/778#issuecomment-1265458751

**Comment by nlf** [comment]
we are generally on track for this target.

since we've already come to an agreement with the node team about landing npm@9 in node 19 specifically by addressing their breaking change concerns manually and directly, the only remaining work here is to submit a pull request on the target date.

**Comment by nlf** [comment]
the nodejs team has landed npm@9 and includes it in the release proposal for node 19.3.0: https://github.com/nodejs/node/pull/45831

at this juncture the release is out of our hands, so i'm closing this issue as complete
