### ISSUE TITLE
Standardize branches in all projects

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#6]
- [x] Create `master`/`develop` branch in all projects
- [x] (Remove/rename) `latest` branch

**Comment by HERBOD7** [comment]
@darcyclarke I can do it.

**Comment by darcyclarke** [comment]
@HERBOD7 Appreciate the enthusiasm! Unfortunately, some of these tasks require specific GitHub permissions which we've only currently given to npm inc. employees. That might change in the future if we're able to permission community contributors in a way to unlocks those types of capabilities.

**Comment by ljharb** [comment]
@darcyclarke re this checklist; it's better if the previous default branch remains deleted forever, so github can properly redirect links to the new default branch.
