### ISSUE TITLE
feat(docs): Improve `docs.npmjs.com` - v2

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#603]
### Summary
Make improvements to `docs.npmjs.com` to allow it to be maintainable. (carried over from https://github.com/npm/statusboard/issues/526)

### Exit Criteria
- [x] add `CONTRIBUTING.md` - outlining who is responsible for reviewing PRs vs. style/theme updates (only one team should own this)
- [ ] add `npm query` inline demo
  - [ ] Create browser friendly bundle of arborist/query-selector-all
  - [ ] Use `react-live` component from `primer/doctocat` to run bundled query code
  - [ ] Create ~3-5 predefined arborist trees to query against
- [x] Use `primer/doctocat` upstream docs theme `TODO: add tracking PR`
  - [x] Make PR to `primer/doctocat` with upstream changes needed
  - [x] Install `primer/doctocat` and use Gatsby theme shadowing for any needed changes in `npm/documentation`
- [x] Upate to mdx v2 with breaking content changes
- [x] investigate leveraging Gatsby's existing cache for builds

**Comment by lukekarrys** [comment]
Closing this since it is all complete outside of the query demo which is no longer happening.
