### ISSUE TITLE
Flag to change exit status of `npm query`

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#609]
We had discussed a flag that will allow folks to deterministically respond to the results of an `npm query` command, specifically exiting with a status code if there are results, or if there are no results.

The naming of the flags is pretty trivial to change, the bulk of the work is simply implementing them.  We can bikeshed the flag name as we go.

**Comment by wojpawlik** [comment]
`git` uses `--exit-code`, jq `--exit-status`. I'd be fine with either.

Isn't implementation just adding 7 lines to  https://github.com/npm/cli/blob/latest/lib/commands/query.js ?

**Comment by wraithgar** [comment]
https://github.com/npm/cli/pull/5966
