### ISSUE TITLE
ADR, Scope and identify engg tasks for Audit Policies and Filters

### ISSUE THREAD

**Issue by saquibkhan** [npm/statusboard#622]
ADR/Design Doc ready

## Exit Criteria
- ADR/Design Doc ready
- We can partner with security team early on #npm-support channel
- Later we should do formal security review

Stretch
- customer research
- there is scope to collaborate with dependabot team and see if they can adopt this solution, if dependabot can also respect these policies.

cc @MylesBorins

**Comment by saquibkhan** [comment]
We can partner with security team on #npm-support channel

Later we should do formal security review

**Comment by ljharb** [comment]
Is there any reason these drafts can't be publicly shared? That would get you "customer research" for free via public comment.

**Comment by saquibkhan** [comment]
In my opinion draft can be made publicly available

**Comment by lukekarrys** [comment]
# Epic

## Motivation

There have been many past RFCs addressing `npm audit` and it's need for configurability. Some of the prior art here includes:

- **Audit Assertions** (https://github.com/npm/rfcs/pull/422) which at a high level was proposed to allow module authors and users to configure which advisories `npm audit` surfaced applied to a particular project
- **Audit Queries/Filters** (https://github.com/npm/rfcs/pull/636) proposed using `--query` flag to configure which packages in a tree would get audited
- **Audit Policies** (https://github.com/npm/rfcs/pull/637) proposed a configurable set of audit queries that would gate the dependency graph reification process to fail if packages prohibited by a policy were attempted to install
- **Only Registry Dependencies** (https://github.com/npm/rfcs/pull/593): proposed a flag that would cause `npm install` (and similar commands) to fail when attempting to install packages not from a specific registry
- **Recommend Unique for packages** (https://github.com/npm/rfcs/issues/649) proposed a package.json flag to warn a user that a package should be unique within a dependency graph

This RFC does not specifically supersede any of the above RFCs, but instead is being used as a high level outline of the future plans of `npm audit` and net new behavior of blocking installs based on auditable packages.

The purpose of this RFC is to create a sustainable base that will give the ecosystem the building blocks to implement features like "Only Registry Dependencies", "Recommend Unique" and a subset of "Audit Assertions:.

## Exit Criteria

- An audit configuration config that can live in a file at the root of a project or within its package.json
- An audit configuration spec that can be parsed or written to by humans, `npm`, or other tools
- A CLI flag for `audit` that will act as a single audit policy
- A way to gate installs/updates to fail or warn if audit policies are not met

## Implementation

The audit policy spec is unchanged from it's proposal in https://github.com/npm/rfcs/pull/637:

```json
{
    "audit": {
        "policies": [
            {
                "name": "Vulnerable",
                "type": "error",
                "query": ":vulnerable"
            },
            {
                "name": "Peer Conflicts",
                "type": "error",
                "query": ".peer:not(:deduped)"
            },
            {
                "name": "Deprecated",
                "type": "warn",
                "query": ":deprecated"
            },
            {
                "name": "Outdated",
                "type": "log",
                "query": ":outdated()"
            },
            {
                "name": "Licenses",
                "type": "log",
                "query": ":not([license=MIT])"
            },
            {
                "name": "Remotes",
                "type": "error",
                "query": ":type(git), :type(remote)"
            },
            {
                "name": "Extraneous",
                "type": "warn",
                "query": ":extraneous"
            },
            {
                "name": "Missing",
                "type": "warn",
                "query": ":missing"
            },
            {
                "name": "Duplicate Peers",
                "type": "warn",
                "query": ".peer:not(:deduped)"
            },
            {
                "name": "Bad Packages",
                "type": "error",
                "query": "#phishing, #spam, #malware"
            },
            {
                "name": "Bad Actors",
                "type": "error",
                "query": ":attr(contributors, [email=bad@example.com])"
            },
            {
                "name": "Architecture Mismatch",
                "type": "error",
                "query": "@supports(cpu:x64) { [cpu=!x64] }"
            }
        ]
    }
}
```

## Non-Goals

## Feature Ideas

**Comment by lukekarrys** [comment]
New RFC has been opened for public discussion including an implementation/design for the feature. Closing this issue and continuing to track in the initiative issue #345
