### ISSUE TITLE
npm query invalid signature refactor

### ISSUE THREAD

**Issue by wraithgar** [npm/statusboard#623]
We need to break out the invalid signature error handling to be able to account for integrity errors alongside provenance errors.  For now provenance errors will be thrown from the audit command but that code should be implemented in a way that's easy to move to pacote once sigstore 1.0 lands

**Comment by saquibkhan** [comment]
TBD on me: Add to provenance link

**Comment by saquibkhan** [comment]
@navin22 @feelepxyz for visibility.

After discussing with @wraithgar came to know that this issue could become a blocker for provenance relase.

**Comment by navin22** [comment]
@wraithgar Is it more about refactoring ? or will this be a blocker for Feb 15th private beta?

/cc: @feelepxyz @bdehamer

**Comment by wraithgar** [comment]
This is for the `npm audit signatures` command, not for the publishing with provenance.

**Comment by wraithgar** [comment]
the provenance branch is now ready for attestation validation during `npm audit signatures`.  the code can push distinct objects onto the invalid array and then add special code during the printing of the invalid entries to display the right info, whenever the provenance team is ready.

**Comment by feelepxyz** [comment]
@wraithgar this sounds great! Is the plan to still move the audit attestation logic to pacote? And this is blocked on sigstore-js 1.0 so we can add it as a dependency there and publish a new pacote release? 

Was there any risk getting this in for the private beta release or is this moot given what you just shipped?

**Comment by wraithgar** [comment]
Yes, the plan is still to move it into pacote once sigstore-js is in 1.0.0.  The code lives in the audit command itself and is pretty well grouped together for ease of movement.

There is no risk for private beta release.  This was a change to the `npm audit` command in isolation and didn't really touch any of the other code.  All of the tests are still passing in the branch, the only code that's currently ignored for coverage is this new audit check. 

I kept this new code in a separate commit, so that when we go to land it in `latest` on the cli it could be included or omitted based on how far along we got.  If it's not ready we can land only the `publish` provenance code.

**Comment by feelepxyz** [comment]
> I kept this new code in a separate commit, so that when we land the `provenance` branch in `latest` on the cli it could be included or omitted based on how far along we got. If it's not ready we can land only the `publish` provenance code.

Ace. This sounds like a great plan to me! 👍
