### ISSUE TITLE
Update dependencies v1

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#65]
- [1] pacote@10.3.1 ☑️
- ~~@npmcli/installed-package-contents@1.0.5 ~~ (not a dep of cli)
- [1] cacache@14.0.0  ☑️
- ~~chownr@1.1.3 ~~ (already up-to-date)
- ~~[2] fs-minipass@2.1.0  ☑️~~ (will be updated by other deps)
- ~~[2] infer-owner@1.0.4  ☑️~~ (already up-to-date)
- ~~[3] lru-cache@5.1.1  ☑️~~ (already up-to-date)
- ~~[3] minipass@3.1.1  ☑️~~ (will be updated by other deps)
- ~~minipass-fetch@1.2.1  (not a dep of cli)~~
- [3] mkdirp@1.0.3  ☑️
- [3] npm-package-arg@8.0.0  ☑️
- [2] npm-packlist@2.0.3  ☑️
- [2] npm-pick-manifest@5.0.0  ☑️
- [2] npm-registry-fetch@6.0.0  ☑️
- ~~[3] osenv@0.1.5  ☑️~~ (already up-to-date)
- ~~promise-inflight@1.0.1~~  (already up-to-date)
- ~~promise-retry@1.1.1 ~~ (will be updated by other deps)
- ~~read-package-json-fast@1.1.3 ~~ (not a dep of cli)
- [3] semver@7.1.1  ☑️
- [3] ssri@7.1.0  ☑️
- [1] tar@6.0.0  (before `pacote`)
- [3] which@2.0.2 ☑️

### Approach to Update

1. Create [epic branch](https://github.com/npm/cli/tree/feature/update-deps-v1)
2. Create tickets for each dep to update
3. Fork from epic branch, and update dep on their own branchs; target pull-request into epic branch
4. Target pull-request for epic branch, into [v7-beta branch](https://github.com/npm/cli/tree/release/v7.0.0-beta)

##### Group 3 (group all these deps into a single branch)
- npm-package-arg
- semver
- ssri
- which
##### Group 2 (_probably_ can group deps into a single branch)
- npm-registry-fetch
- npm-pick-manifest
- npm-packlist
##### Group 1 (these deps should have their own branch)
- pacote
- tar
- cacache
- mkdirp

## Update Flow
- checkout group branch
- run `npm ls {dep-name}`; validate tree (should see dep at root level)
- note other deps in tree, any deps not in current v1 list, should be added to comment below
- run `scripts/dep-update {dep-name} {latest-version}`
- run `npm test` (validate all tests pass)
- run `npm ls {dep-name}` again, validate tree change
- push commit to group branch

## Update Procedure
When updating dependencies, it really matters what the current state of the `node_modules/` folder and `package-lock.json` file look like, as the update builds off of this information _(read: state)_. Therefore, merging in sets of dependency updates results in lots of conflicts, which can't be easily solved, or the resolution, isn't _technically_ correct.

Given the above, we are going to update the deps one at a time, on the [epic branch](https://github.com/npm/cli/tree/feature/update-deps-v1) we created, so as to preserve this state and be able to manage the updates well.

**Comment by mikemimik** [comment]
## Potential v2 Deps
- libnpmaccess
- libnpm (likely be replaced by pacote)
- libcipm (likely be replaced by arborist)
- init-package-json
- libnpx (likely to get a refactor)
- lock-verify (likely replaced by arborist)
