### ISSUE TITLE
Standardize PR/Issue templates on all projects

### ISSUE THREAD

**Issue by darcyclarke** [npm/statusboard#7]
- [x] use the `.github` issue template from `npm/cli`

**Comment by HERBOD7** [comment]
@darcyclarke I can do it.

**Comment by darcyclarke** [comment]
@HERBOD7 Appreciate the enthusiasm! We still have some internal discussion to take place before we decide which projects are actually appropriate to extend the defaults; With that in mind, we'll probably assign this to someone on our team.

**Comment by lukekarrys** [comment]
This is done via `@npmcli/template-oss`!
