### ISSUE TITLE
[BUG] query command returns incomplete dependency list for workspaces

### ISSUE THREAD

**Issue by bdehamer** [npm/statusboard#703]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Assuming the following project set-up:
```
$ cat package.json 
{
  "name": "root",
  "version": "1.0.0",
  "workspaces": ["./a", "./b"]
}

$ npm ls -all
root@1.0.0 /private/tmp/root
├─┬ a@1.0.0 -> ./a
│ └── b@1.0.0 deduped -> ./b
└─┬ b@1.0.0 -> ./b
  └── lodash@4.17.21
```

Run the query:
```
$  npm query '#a *' | jq '.[].name'
```

The only returned result is:
```
"b"
```

### Expected Behavior

Run the query:
```
$  npm query '#a *' | jq '.[].name'
```

The returned result should be:
```
"b"
"lodash"
```

Similar to the result returned from `npm-ls` with the `--workspace` flag:
```
$ npm ls --workspace a
root@1.0.0 /private/tmp/root
└─┬ a@1.0.0 -> ./a
  └─┬ b@1.0.0 -> ./b
    └── lodash@4.17.21
```

### Steps To Reproduce

Set-up the following directory structure:

```
root
├── a
│   └── package.json
├── b
│   └── package.json
└── package.json
```

In the _root_ directory, create the following _package.json_ file:
```json
{
  "name": "root",
  "version": "1.0.0",
  "workspaces": ["./a", "./b"]
}
```

In the _a_ directory, create the following _package.json_ file:
```json
{
  "name": "a",
  "version": "1.0.0",
  "dependencies": {
    "b": "1.0.0"
  }
}
```

In the _b_ directory, create the following _package.json_ file:
```json
{
  "name": "b",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
```

Execute the following:
```
$ npm query '#a *' | jq '.[].name'
"b"
```

Note that `b` is returned but NOT `lodash`

### Environment

- npm: 10.0.0
- Node: v18.12.1
- OS: macOS
- platform: arm64

**Comment by ljharb** [comment]
@bdehamer i think you meant to file this on npm/cli and not on the statusboard repo? (you can transfer it if you have Write permissions on both, i believe)

**Comment by wraithgar** [comment]
No I asked him to put it here

**Comment by ljharb** [comment]
alrighty then, seems like an odd place but glad it's intended :-)

**Comment by wraithgar** [comment]
https://github.com/npm/cli/blob/latest/workspaces/arborist/lib/query-selector-all.js#L721-L723
and
https://github.com/npm/cli/blob/latest/workspaces/arborist/lib/query-selector-all.js#L699-L702

appear to be the culprit(s), they assume only the root can have linked descendants, which is not true in the world of workspaces.

**Comment by bdehamer** [comment]
I spent some time poking at this and definitely think the issue is in the [`hasParent`](https://github.com/npm/cli/blob/latest/workspaces/arborist/lib/query-selector-all.js#L696) function.

For the test case above, when the `lodash` package is evaluated, the logic recursively walks up the `edgesIn` collection to see if it can find a path to `a`. It can get from `lodash` to the `b` node . . . but that node has no further `edgesIn` to follow.

A rough sketch of what the list of nodes looks like for this project:
```
ArboristNode{
  name: root
  edgesOut: [ ArboristLink{ name: 'a' }, ArboristLink{ name: 'b' }
  edgesIn: []
}

ArboristLink{
  name: a
  edgesOut: []
  edgesIn: [ ArboristNode{ name: 'root' } ]
  target: ArboristNode{ name: 'a' }
}

ArboristLink{
  name: b
  edgesOut: []
  edgesIn: [ ArboristNode{ name: 'a' }, ArboristNode{ name: 'root' } ]
  target: ArboristNode{ name: 'b' }
}

ArboristNode{
  name: a
  edgesOut: [ ArboristLink{ name: b } ]
  edgesIn: []
}

ArboristNode{
  name: b  
  edgesOut: [ ArboristNode{ name: lodash } ]
  edgesIn: []
}

ArboristNode{
  name: lodash
  edgesOut: []
  edgesIn: [ ArboristNode{ name: b } ]
}
```

Each of the workspaces have both an `ArboristNode` and `ArboristLink` -- while you can follow `b`'s `Link` back to the `a` workspace, you can't do so from `b`'s `Node`. Given that workspace `Node`s don't appear to have any reference to their corresponding `Link`, it's not always possible to move up the tree from a leaf all the way to the root.
