### ISSUE TITLE
Packages should be able to be written in TypeScript + published as ESM+CJS

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#738]
Template OSS PR: https://github.com/npm/template-oss/pull/371
Read PR: https://github.com/npm/read/pull/77https://github.com/npm/read/pull/77

**Comment by ljharb** [comment]
why native ESM? that means nobody who uses CJS will be able to use it.

**Comment by lukekarrys** [comment]
> why native ESM? that means nobody who uses CJS will be able to use it.

just updated the title which i typed too quickly. our goal is to be able to author in typescript and then publish ESM/CJS with [`tshy`](https://github.com/isaacs/tshy).

**Comment by lukekarrys** [comment]
## Weekly Status 
### Overall status: 

🟢 Normal


### Target date

2023-12-01

### Accomplishments: 

- Created draft PR to npm/read converting to TS https://github.com/npm/read/pull/77
- Took changes from that PR and refactored them to fit into template-oss https://github.com/npm/template-oss/pull/371
- Made sure new changes landed cleanly in `npm/read` by using template-oss tarball in CI

### Next: 
- Land and publish template-oss
- Land and publish read
### Risks

**Comment by lukekarrys** [comment]
## Weekly Status 
### Overall status: 

🟢 Normal


### Target date

2023-12-01

### Accomplishments: 

- Merged and published read using TypeScript https://github.com/npm/read/pull/77
- Landed TypeScript + ESM configuration in template-oss https://github.com/npm/template-oss/pull/371

### Next: 
- Land last cleanup item on `read` to ensure only `dist/` files are published https://github.com/npm/read/pull/84
- Upstream `dist/` file changes to template-oss which is part of https://github.com/npm/template-oss/pull/380
### Risks
