### ISSUE TITLE
remove figgy-pudding from libnpmteam

### ISSUE THREAD

**Issue by claudiahdz** [npm/statusboard#76]
Tasks
- [x] update badges
- [x] add GHA
- [x] add `settings.yml` to extend from boilerplate
- [x] remove travis, and appvoyer
- [x] update README; remove opts.Promise
- [x] add `"engines"` field to `package.json`
- [x] remove `get-stream`; replace with `minipass`
- [x] update `npm-registry-fetch@4.0.0` -> `8.0.0`
- [x] remove `weallbehave` and `weallcontribute`
- [x] update version of `tap` -> `latest`
- [x] create `"tap"` section in `package.json`
- [x] fix `authors` prop in `package.json`; change to string
- [x] remove `figgy-pudding`
- [x] remove `pwrap` function
- [x] make sure all tests pass
- [x] make sure 100% code coverage

**Comment by mikemimik** [comment]
Tasks
- [ ] update badges
- [ ] add GHA
- [ ] remove travis, and appvoyer
- [ ] update README; remove opts.Promise
- [ ] remove `get-stream`; replace with `minipass`
- [ ] update `npm-registry-fetch@4.0.0` -> `8.0.0`
- [ ] remove `weallbehave` and `weallcontribute`
- [ ] update version of `tap` -> `latest`
- [ ] fix `authors` prop in `package.json`
- [ ] remove `figgy-pudding`
- [ ] remove `pwrap` function
- [ ] make sure all tests pass
- [ ] make sure 100% code coverage
