### ISSUE TITLE
[BUG] <title> @npm/cli link in the Readme.md redirects to https://github.com/orgs/npm/teams/cli which turns to be 404 page not found.

### ISSUE THREAD

**Issue by vr-varad** [npm/statusboard#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The link in the README.md header section :
```A single view to help monitor the status/health of the [`@npm/cli`](https://github.com/orgs/npm/teams/cli) teams's Open Source Projects.```
redirects to a 404 page.

### Expected Behavior

I think it should redirect to either ```https://github.com/npm/cli``` or any other valid URL.

**Comment by lukekarrys** [comment]
This is a private link. It's not ideal to have in a public repo, but helpful for us to have a link to the internal team here.
