### ISSUE TITLE
Deprecate unused+archived `@npmcli` packages

### ISSUE THREAD

**Issue by lukekarrys** [npm/statusboard#849]
Now that we have all our packages on the `@npmcli` team, it was easier to do something I've wanted to do before: map our packages to their GitHub repos and use in the CLI. Using this data as a signal I was able to identify a number of packages I think we should deprecate. All of the deprecations are to match repos that are already archived, although some of the repos were archived as part of my findings here.

There is one outlier `npm-merge-driver` that I'm not sure what to do with. It's usage has been brought up before by other teams at GitHub. The repo is archived, but I'm not sure if it should be officially deprecated on the registry.

**Here are the packages I think we should deprecate and the message we should use to deprecate them:**
| name | downloads | message |
| ------ | --------- | ------ |
| gauge | 85,496,147 | This package is no longer supported. |
| npmlog | 84,944,008 | This package is no longer supported. |
| are-we-there-yet | 84,637,471 | This package is no longer supported. |
| read-package-json | 32,676,257 | This package is no longer supported. Please use @npmcli/package-json instead. |
| fs-write-stream-atomic | 21,872,169 | This package is no longer supported. |
| move-concurrently | 21,800,758 | This package is no longer supported. |
| copy-concurrently | 21,361,080 | This package is no longer supported. |
| osenv | 18,001,523 | This package is no longer supported. |
| fstream | 17,417,284 | This package is no longer supported. |
| uid-number | 3,146,340 | This package is no longer supported. |
| read-installed | 2,997,918 | This package is no longer supported. |
| @npmcli/disparity-colors | 2,018,842 | This package is no longer supported. |
| fstream-ignore | 1,227,570 | This package is no longer supported. |
| libnpx | 826,798 | This package is no longer supported. |
| npm-registry-client | 800,938 | This package is no longer supported. |
| npm-cache-filename | 760,099 | This package is no longer supported. |
| lock-verify | 523,768 | This package is no longer supported. |
| find-npm-prefix | 510,375 | This package is no longer supported. |
| npx | 480,460 | This package is now part of the npm CLI. |
| libnpm | 416,481 | This package is no longer supported. |
| fstream-npm | 251,332 | This package is no longer supported. |
| normalize-git-url | 144,093 | This package is no longer supported. |
| realize-package-specifier | 91,141 | This package is no longer supported. |
| npm-merge-driver | 38,252 | ???? |
| npmc | 11,573 | This package is no longer supported. Please use npm instead. |
| npm-registry-couchapp | 1,424 | This package is no longer supported. |
| cipm | 205 | This package is no longer supported. |
| npm-profile-cli | 16 | This package is no longer supported. |
| fallback-fs | 16 | This package is no longer supported. |
| do-you-even-lift | 15 | This package is no longer supported. |
| @npmcli/infer-owner | 6 | This package is no longer supported. |
| @npmcli/publish-test | 5 | This package is no longer supported. |

---

Below is the full data I used to find the above packages to deprecate.

I went through it all manually since there are no perfect signals here. Eg: some deprecated packages map to active repos and some unused packages are tools that aren't used by the CLI but we don't want to deprecate/archive.

<details><summary>Full Data</summary>
<p>

| pkg                                                                                                | deprecated | unused in CLI | repo                                                                                      | archived | downloads/mo  |
| -------------------------------------------------------------------------------------------------- | ---------- | ------------- | ----------------------------------------------------------------------------------------- | -------- | ------------- |
| [semver](https://npmjs.com/package/semver)                                                         |            |               | [npm/node-semver](https://github.com/npm/node-semver)                                     |          | 1,333,621,524 |
| [which](https://npmjs.com/package/which)                                                           |            |               | [npm/node-which](https://github.com/npm/node-which)                                       |          | 372,810,282   |
| [hosted-git-info](https://npmjs.com/package/hosted-git-info)                                       |            |               | [npm/hosted-git-info](https://github.com/npm/hosted-git-info)                             |          | 209,001,983   |
| [write-file-atomic](https://npmjs.com/package/write-file-atomic)                                   |            |               | [npm/write-file-atomic](https://github.com/npm/write-file-atomic)                         |          | 207,866,405   |
| [ini](https://npmjs.com/package/ini)                                                               |            |               | [npm/ini](https://github.com/npm/ini)                                                     |          | 188,217,804   |
| [normalize-package-data](https://npmjs.com/package/normalize-package-data)                         |            |               | [npm/normalize-package-data](https://github.com/npm/normalize-package-data)               |          | 174,741,486   |
| [json-parse-even-better-errors](https://npmjs.com/package/json-parse-even-better-errors)           |            |               | [npm/json-parse-even-better-errors](https://github.com/npm/json-parse-even-better-errors) |          | 172,327,972   |
| [nopt](https://npmjs.com/package/nopt)                                                             |            |               | [npm/nopt](https://github.com/npm/nopt)                                                   |          | 137,957,775   |
| [ssri](https://npmjs.com/package/ssri)                                                             |            |               | [npm/ssri](https://github.com/npm/ssri)                                                   |          | 123,397,106   |
| [cacache](https://npmjs.com/package/cacache)                                                       |            |               | [npm/cacache](https://github.com/npm/cacache)                                             |          | 120,926,092   |
| [mute-stream](https://npmjs.com/package/mute-stream)                                               |            |               | [npm/mute-stream](https://github.com/npm/mute-stream)                                     |          | 114,389,430   |
| [abbrev](https://npmjs.com/package/abbrev)                                                         |            |               | [npm/abbrev-js](https://github.com/npm/abbrev-js)                                         |          | 104,995,866   |
| [gauge](https://npmjs.com/package/gauge)                                                           | 🔄         | ✅            | [npm/gauge](https://github.com/npm/gauge)                                                 | ✅       | 88,510,705    |
| [npmlog](https://npmjs.com/package/npmlog)                                                         | 🔄         | ✅            | [npm/npmlog](https://github.com/npm/npmlog)                                               | ✅       | 87,942,806    |
| [unique-slug](https://npmjs.com/package/unique-slug)                                               |            |               | [npm/unique-slug](https://github.com/npm/unique-slug)                                     |          | 87,644,950    |
| [are-we-there-yet](https://npmjs.com/package/are-we-there-yet)                                     | 🔄         | ✅            | [npm/are-we-there-yet](https://github.com/npm/are-we-there-yet)                           | ✅       | 87,624,644    |
| [unique-filename](https://npmjs.com/package/unique-filename)                                       |            |               | [npm/unique-filename](https://github.com/npm/unique-filename)                             |          | 87,376,817    |
| [make-fetch-happen](https://npmjs.com/package/make-fetch-happen)                                   |            |               | [npm/make-fetch-happen](https://github.com/npm/make-fetch-happen)                         |          | 79,043,150    |
| [@npmcli/fs](https://npmjs.com/package/@npmcli/fs)                                                 |            |               | [npm/fs](https://github.com/npm/fs)                                                       |          | 75,174,492    |
| [minipass-fetch](https://npmjs.com/package/minipass-fetch)                                         |            |               | [npm/minipass-fetch](https://github.com/npm/minipass-fetch)                               |          | 71,253,089    |
| [npm-package-arg](https://npmjs.com/package/npm-package-arg)                                       |            |               | [npm/npm-package-arg](https://github.com/npm/npm-package-arg)                             |          | 58,610,162    |
| [validate-npm-package-name](https://npmjs.com/package/validate-npm-package-name)                   |            |               | [npm/validate-npm-package-name](https://github.com/npm/validate-npm-package-name)         |          | 57,975,357    |
| [npm-normalize-package-bin](https://npmjs.com/package/npm-normalize-package-bin)                   |            |               | [npm/npm-normalize-package-bin](https://github.com/npm/npm-normalize-package-bin)         |          | 56,232,129    |
| [proc-log](https://npmjs.com/package/proc-log)                                                     |            |               | [npm/proc-log](https://github.com/npm/proc-log)                                           |          | 50,617,515    |
| [@npmcli/move-file](https://npmjs.com/package/@npmcli/move-file)                                   | ✅         | ✅            | [npm/move-file](https://github.com/npm/move-file)                                         | ✅       | 45,669,180    |
| [ignore-walk](https://npmjs.com/package/ignore-walk)                                               |            |               | [npm/ignore-walk](https://github.com/npm/ignore-walk)                                     |          | 41,525,337    |
| [npm-bundled](https://npmjs.com/package/npm-bundled)                                               |            |               | [npm/npm-bundled](https://github.com/npm/npm-bundled)                                     |          | 39,434,268    |
| [npm-packlist](https://npmjs.com/package/npm-packlist)                                             |            |               | [npm/npm-packlist](https://github.com/npm/npm-packlist)                                   |          | 39,316,526    |
| [npm-registry-fetch](https://npmjs.com/package/npm-registry-fetch)                                 |            |               | [npm/npm-registry-fetch](https://github.com/npm/npm-registry-fetch)                       |          | 34,025,512    |
| [read-package-json](https://npmjs.com/package/read-package-json)                                   | 🔄         | ✅            | [npm/read-package-json](https://github.com/npm/read-package-json)                         | ✅       | 33,861,661    |
| [npm-pick-manifest](https://npmjs.com/package/npm-pick-manifest)                                   |            |               | [npm/npm-pick-manifest](https://github.com/npm/npm-pick-manifest)                         |          | 33,359,278    |
| [pacote](https://npmjs.com/package/pacote)                                                         |            |               | [npm/pacote](https://github.com/npm/pacote)                                               |          | 31,563,760    |
| [@npmcli/promise-spawn](https://npmjs.com/package/@npmcli/promise-spawn)                           |            |               | [npm/promise-spawn](https://github.com/npm/promise-spawn)                                 |          | 30,635,700    |
| [@npmcli/run-script](https://npmjs.com/package/@npmcli/run-script)                                 |            |               | [npm/run-script](https://github.com/npm/run-script)                                       |          | 30,569,737    |
| [@npmcli/git](https://npmjs.com/package/@npmcli/git)                                               |            |               | [npm/git](https://github.com/npm/git)                                                     |          | 30,179,509    |
| [npm-install-checks](https://npmjs.com/package/npm-install-checks)                                 |            |               | [npm/npm-install-checks](https://github.com/npm/npm-install-checks)                       |          | 30,001,004    |
| [read-package-json-fast](https://npmjs.com/package/read-package-json-fast)                         |            |               | [npm/read-package-json-fast](https://github.com/npm/read-package-json-fast)               |          | 29,838,478    |
| [@npmcli/node-gyp](https://npmjs.com/package/@npmcli/node-gyp)                                     |            |               | [npm/node-gyp](https://github.com/npm/node-gyp)                                           |          | 27,251,184    |
| [@npmcli/installed-package-contents](https://npmjs.com/package/@npmcli/installed-package-contents) |            |               | [npm/installed-package-contents](https://github.com/npm/installed-package-contents)       |          | 26,714,308    |
| [npm](https://npmjs.com/package/npm)                                                               |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 24,456,981    |
| [fs-write-stream-atomic](https://npmjs.com/package/fs-write-stream-atomic)                         | 🔄         | ✅            | [npm/fs-write-stream-atomic](https://github.com/npm/fs-write-stream-atomic)               | ✅       | 22,699,230    |
| [move-concurrently](https://npmjs.com/package/move-concurrently)                                   | 🔄         | ✅            | [npm/move-concurrently](https://github.com/npm/move-concurrently)                         | ✅       | 22,624,368    |
| [figgy-pudding](https://npmjs.com/package/figgy-pudding)                                           | ✅         | ✅            | [npm/figgy-pudding](https://github.com/npm/figgy-pudding)                                 | ✅       | 22,576,728    |
| [copy-concurrently](https://npmjs.com/package/copy-concurrently)                                   | 🔄         | ✅            | [npm/copy-concurrently](https://github.com/npm/copy-concurrently)                         | ✅       | 22,170,602    |
| [@npmcli/agent](https://npmjs.com/package/@npmcli/agent)                                           |            |               | [npm/agent](https://github.com/npm/agent)                                                 |          | 19,556,833    |
| [read](https://npmjs.com/package/read)                                                             |            |               | [npm/read](https://github.com/npm/read)                                                   |          | 18,947,045    |
| [osenv](https://npmjs.com/package/osenv)                                                           | 🔄         | ✅            | [npm/osenv](https://github.com/npm/osenv)                                                 | ✅       | 18,647,743    |
| [fstream](https://npmjs.com/package/fstream)                                                       | 🔄         | ✅            | [npm/fstream](https://github.com/npm/fstream)                                             | ✅       | 17,996,868    |
| [@npmcli/package-json](https://npmjs.com/package/@npmcli/package-json)                             |            |               | [npm/package-json](https://github.com/npm/package-json)                                   |          | 16,664,558    |
| [read-cmd-shim](https://npmjs.com/package/read-cmd-shim)                                           |            |               | [npm/read-cmd-shim](https://github.com/npm/read-cmd-shim)                                 |          | 13,745,280    |
| [cmd-shim](https://npmjs.com/package/cmd-shim)                                                     |            |               | [npm/cmd-shim](https://github.com/npm/cmd-shim)                                           |          | 13,561,046    |
| [@npmcli/map-workspaces](https://npmjs.com/package/@npmcli/map-workspaces)                         |            |               | [npm/map-workspaces](https://github.com/npm/map-workspaces)                               |          | 10,998,327    |
| [@npmcli/name-from-folder](https://npmjs.com/package/@npmcli/name-from-folder)                     |            |               | [npm/name-from-folder](https://github.com/npm/name-from-folder)                           |          | 10,833,266    |
| [readdir-scoped-modules](https://npmjs.com/package/readdir-scoped-modules)                         | ✅         | ✅            | [npm/readdir-scoped-modules](https://github.com/npm/readdir-scoped-modules)               | ✅       | 10,754,863    |
| [bin-links](https://npmjs.com/package/bin-links)                                                   |            |               | [npm/bin-links](https://github.com/npm/bin-links)                                         |          | 9,709,146     |
| [@npmcli/arborist](https://npmjs.com/package/@npmcli/arborist)                                     |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 8,893,083     |
| [@npmcli/metavuln-calculator](https://npmjs.com/package/@npmcli/metavuln-calculator)               |            |               | [npm/metavuln-calculator](https://github.com/npm/metavuln-calculator)                     |          | 8,776,740     |
| [parse-conflict-json](https://npmjs.com/package/parse-conflict-json)                               |            |               | [npm/parse-conflict-json](https://github.com/npm/parse-conflict-json)                     |          | 8,638,672     |
| [init-package-json](https://npmjs.com/package/init-package-json)                                   |            |               | [npm/init-package-json](https://github.com/npm/init-package-json)                         |          | 7,864,611     |
| [promzard](https://npmjs.com/package/promzard)                                                     |            |               | [npm/promzard](https://github.com/npm/promzard)                                           |          | 7,739,406     |
| [libnpmpublish](https://npmjs.com/package/libnpmpublish)                                           |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 6,977,692     |
| [libnpmaccess](https://npmjs.com/package/libnpmaccess)                                             |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 6,906,998     |
| [@npmcli/redact](https://npmjs.com/package/@npmcli/redact)                                         |            |               | [npm/redact](https://github.com/npm/redact)                                               |          | 5,678,254     |
| [@npmcli/query](https://npmjs.com/package/@npmcli/query)                                           |            |               | [npm/query](https://github.com/npm/query)                                                 |          | 5,202,231     |
| [read-package-tree](https://npmjs.com/package/read-package-tree)                                   | ✅         | ✅            | [npm/read-package-tree](https://github.com/npm/read-package-tree)                         | ✅       | 4,418,231     |
| [stringify-package](https://npmjs.com/package/stringify-package)                                   | ✅         | ✅            | [npm/stringify-package](https://github.com/npm/stringify-package)                         | ✅       | 3,539,385     |
| [@npmcli/config](https://npmjs.com/package/@npmcli/config)                                         |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 3,488,895     |
| [uid-number](https://npmjs.com/package/uid-number)                                                 | 🔄         | ✅            | [npm/uid-number](https://github.com/npm/uid-number)                                       | ✅       | 3,242,552     |
| [read-installed](https://npmjs.com/package/read-installed)                                         | 🔄         | ✅            | [npm/read-installed](https://github.com/npm/read-installed)                               | ✅       | 3,106,998     |
| [npm-user-validate](https://npmjs.com/package/npm-user-validate)                                   |            |               | [npm/npm-user-validate](https://github.com/npm/npm-user-validate)                         |          | 2,883,902     |
| [npm-profile](https://npmjs.com/package/npm-profile)                                               |            |               | [npm/npm-profile](https://github.com/npm/npm-profile)                                     |          | 2,737,728     |
| [libnpmsearch](https://npmjs.com/package/libnpmsearch)                                             |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,676,221     |
| [npm-audit-report](https://npmjs.com/package/npm-audit-report)                                     |            |               | [npm/npm-audit-report](https://github.com/npm/npm-audit-report)                           |          | 2,656,999     |
| [libnpmhook](https://npmjs.com/package/libnpmhook)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,650,027     |
| [libnpmorg](https://npmjs.com/package/libnpmorg)                                                   |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,641,810     |
| [libnpmteam](https://npmjs.com/package/libnpmteam)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,639,256     |
| [@npmcli/ci-detect](https://npmjs.com/package/@npmcli/ci-detect)                                   | ✅         | ✅            | [npm/ci-detect](https://github.com/npm/ci-detect)                                         | ✅       | 2,360,377     |
| [node-fetch-npm](https://npmjs.com/package/node-fetch-npm)                                         | ✅         | ✅            | [npm/node-fetch-npm](https://github.com/npm/node-fetch-npm)                               | ✅       | 2,281,028     |
| [libnpmpack](https://npmjs.com/package/libnpmpack)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,268,053     |
| [libnpmexec](https://npmjs.com/package/libnpmexec)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,253,482     |
| [libnpmversion](https://npmjs.com/package/libnpmversion)                                           |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,248,538     |
| [libnpmfund](https://npmjs.com/package/libnpmfund)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,217,988     |
| [libnpmdiff](https://npmjs.com/package/libnpmdiff)                                                 |            |               | [npm/cli](https://github.com/npm/cli)                                                     |          | 2,217,181     |
| [@npmcli/disparity-colors](https://npmjs.com/package/@npmcli/disparity-colors)                     | 🔄         | ✅            | [npm/disparity-colors](https://github.com/npm/disparity-colors)                           | ✅       | 2,091,264     |
| [npm-lifecycle](https://npmjs.com/package/npm-lifecycle)                                           | ✅         | ✅            | [npm/npm-lifecycle](https://github.com/npm/npm-lifecycle)                                 | ✅       | 1,731,168     |
| [fstream-ignore](https://npmjs.com/package/fstream-ignore)                                         | 🔄         | ✅            | [npm/fstream-ignore](https://github.com/npm/fstream-ignore)                               | ✅       | 1,253,769     |
| [libnpx](https://npmjs.com/package/libnpx)                                                         | 🔄         | ✅            | [npm/npx](https://github.com/npm/npx)                                                     | ✅       | 854,950       |
| [npm-registry-client](https://npmjs.com/package/npm-registry-client)                               | 🔄         | ✅            | [npm/npm-registry-client](https://github.com/npm/npm-registry-client)                     | ✅       | 826,607       |
| [npm-cache-filename](https://npmjs.com/package/npm-cache-filename)                                 | 🔄         | ✅            | [npm/npm-cache-filename](https://github.com/npm/npm-cache-filename)                       | ✅       | 784,264       |
| [fs-vacuum](https://npmjs.com/package/fs-vacuum)                                                   | ✅         | ✅            | [npm/fs-vacuum](https://github.com/npm/fs-vacuum)                                         | ✅       | 764,859       |
| [proggy](https://npmjs.com/package/proggy)                                                         |            |               | [npm/proggy](https://github.com/npm/proggy)                                               |          | 565,597       |
| [lock-verify](https://npmjs.com/package/lock-verify)                                               | 🔄         | ✅            | [npm/lock-verify](https://github.com/npm/lock-verify)                                     | ✅       | 542,075       |
| [find-npm-prefix](https://npmjs.com/package/find-npm-prefix)                                       | 🔄         | ✅            | [npm/find-npm-prefix](https://github.com/npm/find-npm-prefix)                             | ✅       | 528,037       |
| [gentle-fs](https://npmjs.com/package/gentle-fs)                                                   | ✅         | ✅            | [npm/gentle-fs](https://github.com/npm/gentle-fs)                                         | ✅       | 523,407       |
| [npx](https://npmjs.com/package/npx)                                                               | 🔄         | ✅            | [npm/npx](https://github.com/npm/npx)                                                     | ✅       | 491,908       |
| [libcipm](https://npmjs.com/package/libcipm)                                                       | ✅         | ✅            | [npm/libcipm](https://github.com/npm/libcipm)                                             | ✅       | 480,044       |
| [libnpm](https://npmjs.com/package/libnpm)                                                         | 🔄         | ✅            | [npm/libnpm](https://github.com/npm/libnpm)                                               | ✅       | 432,430       |
| [fstream-npm](https://npmjs.com/package/fstream-npm)                                               | 🔄         | ✅            | [npm/fstream-npm](https://github.com/npm/fstream-npm)                                     | ✅       | 257,784       |
| [normalize-git-url](https://npmjs.com/package/normalize-git-url)                                   | 🔄         | ✅            | [npm/normalize-git-url](https://github.com/npm/normalize-git-url)                         | ✅       | 148,943       |
| [realize-package-specifier](https://npmjs.com/package/realize-package-specifier)                   | 🔄         | ✅            | [npm/realize-package-specifier](https://github.com/npm/realize-package-specifier)         | ✅       | 94,322        |
| [npm-registry-mock](https://npmjs.com/package/npm-registry-mock)                                   | ✅         | ✅            | [npm/npm-registry-mock](https://github.com/npm/npm-registry-mock)                         | ✅       | 69,858        |
| [npm-merge-driver](https://npmjs.com/package/npm-merge-driver)                                     | ❓         | ✅            | [npm/npm-merge-driver](https://github.com/npm/npm-merge-driver)                           | ✅       | 39,392        |
| [@npmcli/eslint-config](https://npmjs.com/package/@npmcli/eslint-config)                           |            |               | [npm/eslint-config](https://github.com/npm/eslint-config)                                 |          | 37,459        |
| [@npmcli/template-oss](https://npmjs.com/package/@npmcli/template-oss)                             |            |               | [npm/template-oss](https://github.com/npm/template-oss)                                   |          | 37,151        |
| [npmc](https://npmjs.com/package/npmc)                                                             | 🔄         | ✅            | [npm/cli](https://github.com/npm/cli)                                                     |          | 11,909        |
| [minify-registry-metadata](https://npmjs.com/package/minify-registry-metadata)                     |            |               | [npm/minify-registry-metadata](https://github.com/npm/minify-registry-metadata)           |          | 6,944         |
| [@npmcli/release-please](https://npmjs.com/package/@npmcli/release-please)                         | ✅         | ✅            | [googleapis/release-please](https://github.com/googleapis/release-please)                 |          | 2,769         |
| [dot-prop-legacy](https://npmjs.com/package/dot-prop-legacy)                                       | ✅         | ✅            | [ruyadorno/dot-prop](https://github.com/ruyadorno/dot-prop)                               | ✅       | 1,529         |
| [npm-registry-couchapp](https://npmjs.com/package/npm-registry-couchapp)                           | 🔄         | ✅            | [npm/npm-registry-couchapp](https://github.com/npm/npm-registry-couchapp)                 | ✅       | 1,452         |
| [node-tar](https://npmjs.com/package/node-tar)                                                     | ✅         | ✅            |                                                                                           |          | 1,385         |
| [node-semver](https://npmjs.com/package/node-semver)                                               | ✅         | ✅            |                                                                                           |          | 1,288         |
| [@npmcli/lint](https://npmjs.com/package/@npmcli/lint)                                             | ✅         | ✅            | [npm/lint](https://github.com/npm/lint)                                                   | ✅       | 784           |
| [node-which](https://npmjs.com/package/node-which)                                                 | ✅         | ✅            |                                                                                           |          | 758           |
| [cipm](https://npmjs.com/package/cipm)                                                             | 🔄         | ✅            | [npm/libcipm](https://github.com/npm/libcipm)                                             | ✅       | 215           |
| [@npmcli/tap-nock](https://npmjs.com/package/@npmcli/tap-nock)                                     |            | ✅            | [npm/tap-nock](https://github.com/npm/tap-nock)                                           |          | 145           |
| [Npm](https://npmjs.com/package/Npm)                                                               | ✅         | ✅            | [npm/deprecate-holder](https://github.com/npm/deprecate-holder)                           |          | 45            |
| [do-you-even-lift](https://npmjs.com/package/do-you-even-lift)                                     | 🔄         | ✅            | [npm/do-you-even-lift](https://github.com/npm/do-you-even-lift)                           | ✅       | 16            |
| [npm-profile-cli](https://npmjs.com/package/npm-profile-cli)                                       | 🔄         | ✅            | [npm/npm-profile](https://github.com/npm/npm-profile)                                     |          | 16            |
| [@npmcli/stafftools](https://npmjs.com/package/@npmcli/stafftools)                                 |            | ✅            | [npm/stafftools](https://github.com/npm/stafftools)                                       |          | 15            |
| [@npmcli/pull](https://npmjs.com/package/@npmcli/pull)                                             | ✅         | ✅            | [npm/pull](https://github.com/npm/pull)                                                   | ✅       | 13            |
| [fallback-fs](https://npmjs.com/package/fallback-fs)                                               | 🔄         | ✅            | [npm/fallback-fs](https://github.com/npm/fallback-fs)                                     | ✅       | 9             |
| [@npmcli/create-oss](https://npmjs.com/package/@npmcli/create-oss)                                 |            | ✅            | [npm/create-oss](https://github.com/npm/create-oss)                                       |          | 8             |
| [@npmcli/npm-birthday](https://npmjs.com/package/@npmcli/npm-birthday)                             | ✅         | ✅            | [npm/npm-birthday](https://github.com/npm/npm-birthday)                                   | ✅       | 8             |
| [@npmcli/infer-owner](https://npmjs.com/package/@npmcli/infer-owner)                               | 🔄         | ✅            | [isaacs/infer-owner](https://github.com/isaacs/infer-owner)                               |          | 6             |
| [@npmcli/generate-provenance](https://npmjs.com/package/@npmcli/generate-provenance)               |            | ✅            | [npm/provenance](https://github.com/npm/provenance)                                       |          | 2             |
| [@npmcli/provenance-cli](https://npmjs.com/package/@npmcli/provenance-cli)                         |            | ✅            | [npm/provenance](https://github.com/npm/provenance)                                       |          | 2             |
| [@npmcli/publish-test](https://npmjs.com/package/@npmcli/publish-test)                             | 🔄         | ✅            | [npm/publish-test](https://github.com/npm/publish-test)                                   | ✅       | 2             |

</p>
</details>

**Comment by wraithgar** [comment]
`npm-merge-driver` is a standalone bin that is not really related to the automated merge resolution that npm does internally.  It would take a bit of work to get it up to working condition again, namely we would want to `spawk` what it does now and enforce it, and then we could clean it up.  I don't know if this is a priority however. It may just have to be kept on the backlog for now.

**Comment by lukekarrys** [comment]
In handy script form to run:

```
#!/usr/bin/env bash

set -xe

npm deprecate gauge "This package is no longer supported.""
npm deprecate npmlog "This package is no longer supported.""
npm deprecate are-we-there-yet "This package is no longer supported.""
npm deprecate read-package-json "This package is no longer supported. Please use @npmcli/package-json instead.""
npm deprecate fs-write-stream-atomic "This package is no longer supported.""
npm deprecate move-concurrently "This package is no longer supported.""
npm deprecate copy-concurrently "This package is no longer supported.""
npm deprecate osenv "This package is no longer supported.""
npm deprecate fstream "This package is no longer supported.""
npm deprecate uid-number "This package is no longer supported.""
npm deprecate read-installed "This package is no longer supported.""
npm deprecate @npmcli/disparity-colors "This package is no longer supported.""
npm deprecate fstream-ignore "This package is no longer supported.""
npm deprecate libnpx "This package is no longer supported.""
npm deprecate npm-registry-client "This package is no longer supported.""
npm deprecate npm-cache-filename "This package is no longer supported.""
npm deprecate lock-verify "This package is no longer supported.""
npm deprecate find-npm-prefix "This package is no longer supported.""
npm deprecate npx "This package is now part of the npm CLI.""
npm deprecate libnpm "This package is no longer supported.""
npm deprecate fstream-npm "This package is no longer supported.""
npm deprecate normalize-git-url "This package is no longer supported.""
npm deprecate realize-package-specifier "This package is no longer supported.""
npm deprecate npmc "This package is no longer supported. Please use npm instead.""
npm deprecate npm-registry-couchapp "This package is no longer supported.""
npm deprecate cipm "This package is no longer supported.""
npm deprecate npm-profile-cli "This package is no longer supported.""
npm deprecate fallback-fs "This package is no longer supported.""
npm deprecate do-you-even-lift "This package is no longer supported.""
npm deprecate @npmcli/infer-owner "This package is no longer supported.""
npm deprecate @npmcli/publish-test "This package is no longer supported.""
```

**Comment by wraithgar** [comment]
Thanks @lukekarrys I'll run that ... not on a weekend.

**Comment by wraithgar** [comment]
Gonna make a back-burner issue for `npm-merge-driver` separately

**Comment by wraithgar** [comment]
https://github.com/npm/statusboard/issues/854
