### ISSUE TITLE
[BUG] NPMJS (and Yarn for that matter) registry is having random failures.

### ISSUE THREAD

**Issue by tryvin** [npm/statusboard#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `yarn install` or `npm install` I get random "network errors" from the registry, making my installs to fail.

I have seen all sorts of errors, but it looks like it's something in the backend, see this:

```
#31 427.9 error https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/usr/local/share/.cache/yarn/v6/npm-lodash-4.17.21-679591c564c3bffaae8454cf0b3df370c3d6911c-integrity/node_modules/lodash/_escapeStringChar.js'"
```

### Expected Behavior

That the install works all the time.

### Steps To Reproduce

1. Run `npm install` or `yarn install`
2. See error...

### Environment

- npm: 9.6.7
- Node: v18.17.1
- OS: MacOS 13.6.4 / Linux too
- platform: Macbook Pro / Github Actions

**Comment by lukekarrys** [comment]
This repo is for tracking our future roadmap. For registry issues please contact npm support at https://www.npmjs.com/support
